name: Sync Markdown to Notion

on:
  push:
    branches:
      - main # Triggers the action every time you push/merge to main

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push changed markdown to Notion
        uses: step-security/push-md-to-notion@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}